version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: qwe
  backend:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
